version: '3.9'

services:
  web:
      build: .
      command: sh -c "echo `date` && echo 'Michał Zadrąg port 3000 ' && node server.js"
      volumes:
        - .:/code/
        - /code/node_modules
      ports:
        - "3000:3000"